name: C++ Code Quality

# Run cppcheck on src_c changes to master branch, or any PR to master.
on:
  # on commit
  push:
    branches: master
    paths:
      - 'src/**'

  pull_request:
    branches: master
    paths:
      - 'src/**'

jobs:
  run-cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-mark hold grub-efi-amd64-signed
          sudo apt-get update --fix-missing
          sudo apt-get upgrade
          sudo apt install cppcheck
      - name: Run Static Checker
        run: cppcheck src_c --force --enable=performance,portability,warning